apiVersion: v1
kind: Pod
metadata:
  name: secret-xfusion
spec:
  containers:
    - name: secret-container-xfusion
      image: fedora:latest
      command: ["sleep", "infinity"]
      volumeMounts:
        - name: secret-volume
          mountPath: /opt/cluster
          readOnly: true
  volumes:
    - name: secret-volume
      secret:
        secretName: ecommerce
