apiVersion: v1
kind: Service
metadata:
  name: httpd-service-datacenter
  namespace: httpd-namespace-datacenter
spec:
  type: NodePort
  selector:
    app: httpd-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30004
