apiVersion: v1
kind: Pod
metadata:
  name: pod-devops
  labels:
    app: devops
spec:
  initContainers:
    - name: init-web-content
      image: busybox
      command: ['sh', '-c', 'cp /config/index.html /mnt/index.html']
      volumeMounts:
        - name: devops-storage
          mountPath: /mnt
        - name: web-config
          mountPath: /config
  containers:
    - name: container-devops
      image: httpd:latest
      volumeMounts:
        - name: devops-storage
          mountPath: /usr/local/apache2/htdocs
  volumes:
    - name: devops-storage
      persistentVolumeClaim:
        claimName: pvc-devops
    - name: web-config
      configMap:
        name: web-content
