apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment-nautilus
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-container
        image: poroko/flask-demo-app:latest
        ports:
        - containerPort: 5000

