apiVersion: v1
kind: Service
metadata:
  name: python-service-nautilus
  namespace: default
spec:
  selector:
    app: python-app
  type: NodePort
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 32345
