apiVersion: v1
kind: Pod
metadata:
  name: volume-share-xfusion
spec:
  volumes:
    - name: volume-share
      emptyDir: {}
  containers:
    - name: volume-container-xfusion-1
      image: fedora:latest
      command: ["/bin/sleep", "3600"]
      volumeMounts:
        - mountPath: /tmp/beta
          name: volume-share
    - name: volume-container-xfusion-2
      image: fedora:latest
      command: ["/bin/sleep", "3600"]
      volumeMounts:
        - mountPath: /tmp/apps
          name: volume-share
